### ISSUE TITLE
Could not detect a suitable backend among ['googlechrome-browser', 'chromium-browser']

### ISSUE THREAD

**Issue by LewisNeal** [flexxui/webruntime#28]
Despite adding path for chrome canary in #27 the chrome-browser still fails:

N:\git\webruntime>webruntime https://www.abc.net.au/ chrome-browser
Traceback (most recent call last):
  File "c:\users\lewisneal\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lewisneal\appdata\local\programs\python\python38\lib\runpy.py", line 87,
in _run_code
    exec(code, run_globals)
  File "C:\Users\lewisneal\AppData\Local\Programs\Python\Python38\Scripts\webruntime.exe\__main__.py", line 7, in <module>
  File "c:\users\lewisneal\appdata\local\programs\python\python38\lib\site-packages\webruntime\__main__.py", line 32, in main
    rt = webruntime.launch(sys.argv[1], sys.argv[2])
  File "c:\users\lewisneal\appdata\local\programs\python\python38\lib\site-packages\webruntime\__init__.py", line 200, in launch
    raise ValueError('Could not detect a suitable backend among %r.' % runtimes)
ValueError: Could not detect a suitable backend among ['googlechrome-browser', 'chromium-browser'].
[end]
![Chrome](https://user-images.githubusercontent.com/6681711/90701666-83c2aa00-e2cc-11ea-905d-675bd352b993.JPG)

**Comment by almarklein** [comment]
I think I've found the source of that error. When the Chrome runtime could not be found, it would still try to use it if it had a cache of it. This is addressed in #29.

This does not solve the original problem. It looks like `_get_google_chrome_exe()` still returns None for you. I'd recommend running the code of that function directly (e.g. in an interactive session) and seeing where it goes wrong.

**Comment by almarklein** [comment]
> It looks like `_get_google_chrome_exe()` still returns None for you.

To clarify, for some reason it still does not find the executable on your system. But this is not something I can look into, unfortunately.
